OutServices.Web/Controllers/CaseController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace OutServices.Web.Controllers
{
    public partial class CaseController : Controller
    {
        public async Task<IActionResult> Index()
        {
            await Task.Run(() => ShowThreadInfo("Task"));
            return View();
        }
        public IActionResult List()
        {
            IEnumerable<string> model = GetJSONSeed();
            return View(model);
        }

        private static void ShowThreadInfo(string s)
        {
            Console.WriteLine("{0} Thread ID: {1}", s, Thread.CurrentThread.ManagedThreadId);
        }

        private IEnumerable<string> GetJSONSeed()
        {
            List<string> returnValue = new List<string>();
            for (int i = 0; i < 5; i++)
            {
                OutSeed item = new OutSeed
                {
                    Number = 12,
                    DateTime = DateTime.Now,
                    TrueFalse = true,
                    ArraySeed = new List<InnerSeed>
                    {
                        new InnerSeed
                        {
                            Content = "Content1",
                            Num = 14
                        },
                        new InnerSeed
                        {
                            Content = "Content2",
                            Num = 785
                        },
                        new InnerSeed
                        {
                            Content = "Content3",
                            Num = 325
                        },
                        new InnerSeed
                        {
                            Content = null,
                            Num = 325
                        }
                    }
                };
                string jsonStr = JsonConvert.SerializeObject(item);
                returnValue.Add(jsonStr);
                returnValue.Add(null);
            }
            returnValue.Add("xxxxx aaaaa cccc dddd");
            return returnValue;
        }
        private struct OutSeed
        {
            public string ID => Guid.NewGuid().ToString();
            public int Number { get; set; }
            public bool TrueFalse { get; set; }
            public DateTime DateTime { get; set; }
            public IEnumerable<InnerSeed> ArraySeed { get; set; }
        }
        private struct InnerSeed
        {
            public string CaseID => Guid.NewGuid().ToString();
            public string Content { get; set; }
            public int Num { get; set; }
        }

    }

}

OutServices.Web/Views/Shared/_Layout.cshtml
@{
    const string id = "OutServices";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <meta name="viewport" content="user-scalable=no, width=device-width">
    <title>@ViewData["Title"] - 外勤服務系統</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Case" asp-action="List" class="navbar-brand">
                    <img src="~/images/Logo/NavBrand-Logo.png" style="color: white; max-width: 30px; margin-top: -3px; display: inline-block;" alt=""/>
                    <span style="margin-left: 5px;">外勤服務系統</span>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Case" asp-action="List">首頁</a></li>
                    <li><a asp-area="Backend" asp-controller="Code" asp-action="Index">代碼</a></li>
                    <li><a asp-area="Backend" asp-controller="Account" asp-action="Management">帳號</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />
    <div class="container body-content" id="@id">
        <partial name="_LayoutGoTop" />
        <partial name="_MessageBox" />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - 外勤服務系統</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

OutServices.Web/Views/Shared/_LayoutGoTop.cshtml
<div id="GoTop">
    <i class="fa fa-angle-up"></i>
</div>

OutServices.Web/Views/Shared/_LayoutStyle.cshtml
<style type="text/css">
    .navbar-default {
        background-color: #3c62e7;
        border-color: #2b32c0;
    }
    .navbar-default .navbar-brand {
        color: #eceef1;
    }
    .navbar-default .navbar-brand:hover,
    .navbar-default .navbar-brand:focus {
        color: #cabbff;
    }
    .navbar-default .navbar-text {
        color: #eceef1;
    }
    .navbar-default .navbar-nav > li > a {
        color: #eceef1;
    }
    .navbar-default .navbar-nav > li > a:hover,
    .navbar-default .navbar-nav > li > a:focus {
        color: #cabbff;
    }
    .navbar-default .navbar-nav > .active > a,
    .navbar-default .navbar-nav > .active > a:hover,
    .navbar-default .navbar-nav > .active > a:focus {
        color: #cabbff;
        background-color: #2b32c0;
    }
    .navbar-default .navbar-nav > .open > a,
    .navbar-default .navbar-nav > .open > a:hover,
    .navbar-default .navbar-nav > .open > a:focus {
        color: #cabbff;
        background-color: #2b32c0;
    }
    .navbar-default .navbar-toggle {
        border-color: #2b32c0;
    }
    .navbar-default .navbar-toggle:hover,
    .navbar-default .navbar-toggle:focus {
        background-color: #2b32c0;
    }
    .navbar-default .navbar-toggle .icon-bar {
        background-color: #eceef1;
    }
    .navbar-default .navbar-collapse,
    .navbar-default .navbar-form {
        border-color: #eceef1;
    }
    .navbar-default .navbar-link {
        color: #eceef1;
    }
    .navbar-default .navbar-link:hover {
        color: #cabbff;
    }

    @@media (max-width: 767px) {
    .navbar-default .navbar-nav .open .dropdown-menu > li > a {
        color: #eceef1;
    }
    .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
    .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
        color: #cabbff;
    }
    .navbar-default .navbar-nav .open .dropdown-menu > .active > a,
    .navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
    .navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
        color: #cabbff;
        background-color: #2b32c0;
    }
    }
    
</style>

OutServices.Web/Views/Shared/_Layout_B4.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <meta name="viewport" content="user-scalable=no, width=device-width">
    <title>@ViewData["Title"] - 外勤服務系統</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <partial name="_LayoutNavStyle" />
    <partial name="_GlobalStyle" />
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Case" asp-action="List" class="navbar-brand">
                    <img src="~/images/Logo/NavBrand-Logo.png" style="color: white; max-width: 30px; margin-top: -3px; display: inline-block;"/>
                    <span style="margin-left: 5px;">外勤服務系統</span>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Case" asp-action="List">首頁</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">關於</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">聯絡人</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <partial name="_LayoutGoTop" />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - 外勤服務系統</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

OutServices.Web/Views/Shared/_MessageBox.cshtml
@{
    const string messageTitle ="----";
    const string closeText = "關閉";
}
<div class="modal fade" id="OutServicesMessage" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <i class="fa fa-times-circle-o" aria-hidden="true"></i>
                </button>
                <h4 class="modal-title">@messageTitle</h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">@closeText</button>
            </div>
        </div>
    </div>
</div>